config/routes.rb
Rails.application.routes.draw do
  resources :musics
  root 'musics#thelist'
end

##### Line 2 -
##### in the terminal:  rails g model Music song:string artist:string
##### is what made it possible for me to manually type "resources :musics" above,
##### and then have all the routes automatically made for me
##### "rake routes" in the terminal allows me to check if they were
##### sucessfully created.

##### Line 3 -
##### I added this because I wanted it to go directly to the "thelist.html.erb"
##### view when you load localhost:3000 in the browser.  "thelist.html.erb"
##### is another view I added in addition to the other normal views, and I had
##### to define in the "musics_controller.rb" in the same way that I defined
##### the index - see the controller for more details.

app/models/music.rb
class Music < ActiveRecord::Base

  validates :song, presence: true, length:
    {minimum: 3, message: "must have at least 3 characters in it"}

    ##Line 3 and 4 - there are 2 parameters set in here. The first checks
    ##to see if there are any characters in the "song" field (from the edit and
    ##new views).  The second checks to see if you have typed at least 3
    ##characters in the "song" field (from the edit and new views).  This is
    ##1 of 2 files needed to make this validation work.  The second batch
    ##of code at the top of the edit and new views on lines 1-9 in each view.
    ##it is not necessary to add the code to both edit and new views to make this work,
    ##unless you want it to work for both creating AND editing the songs.

  validates :artist, presence: true, length:
    {minimum: 4, message: "must have at least 4 characters in it"}

    ##Line 15 and 16 - there are 2 parameters set in here. The first checks
    ##to see if there are any characters in the "artist" field (from the edit and
    ##new views).  The second checks to see if you have typed at least 3
    ##characters in the "artist" field (from the edit and new views).  This is
    ##1 of 2 files needed to make this validation work.  The second batch
    ##of code at the top of the edit and new views on lines 1-9 in each view.
    ##it is not necessary to add the code to both edit and new views to make this work,
    ##unless you want it to work for both creating AND editing the songs.


    ##side note.  I have not played around enough to see how adding a bunch more
    ##validations in here, will affect how it interacts with the code in the new and
    ##edit views on lines 1-9, but for now they interact just fine. 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController

  def index
    @musics = Music.all
  end

  def thelist
    @musics = Music.all
  end   ##I added this as my root path, so when you load the browser,
        ##it simply displays the information without all the links
        ##that are present in "index.html.erb" view.  The "Playlist options"
        ##link in the browser links to the "index.html.erb" file, and is
        ##the only link on that page...which is now the root path. localhost:3000/

  def new
    @music = Music.new
  end

  def create
    @music = Music.new(music_params)
    if
      @music.save
      flash[:created] = "Song Was Successfully Added"
      ##This is the flash message for creating a new song, that is displayed at
      ##the top of the index page after you hit submit while creating a new song.
      ##This is 1 of 2 files needed to make this happen, the other is in the
      ##"application.html.erb" file.  ":created" is a variable set by me, and could
      ##be anything you choose it to be.  The message after "=" is the
      ##message that is displayed at the top of the index page after creating a new song.
      ##it (line 31) redirects to the index page
      redirect_to musics_path
    else
      render :new
    end
  end


  def show
    @music = Music.find(params[:id])
  end

  def edit
    @music = Music.find(params[:id])
  end

  def update
    @music = Music.find(params[:id])
    if
      @music.update(music_params)
      redirect_to musics_path
    else
      render :edit
    end
  end


  def destroy
    Music.destroy(params[:id])
    flash[:deleted] = "Song Was Successfully Deleted"
    ##This is the flash message for deleting a song, that is displayed at
    ##the top of the index page after you remove a song from any of the other pages.
    ##This is 1 of 2 files needed to make this happen, the other is in the
    ##"application.html.erb" file.  ":deleted" is a variable set by me, and could
    ##be anything you choose it to be.  The message after "=" is the
    ##message that is displayed at the top of the index page after deleting or removing a song.
    ##it (line 67) redirects to the index page
    redirect_to musics_path
  end


  private


  def music_params
    params.require(:music).permit(:song, :artist)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Benchmarkt6</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if flash[:created].present? %>
  <%= flash[:created] %>
  <hr>
  <% end %>
                              <!--lines 11-14 are needed to make the flash message
                              work that I talked about in the "music_controller.rb"
                              this one is related to the "def create" part of the
                              controller. See the comments in the "music_controller.rb"
                              file for more information.  I am not sure if they need to
                              be above the <%= yield %> but it works this way for sure-->


  <% if flash[:deleted].present? %>
  <%= flash[:deleted] %>
  <hr>
  <% end %>
                              <!--lines 23-26 are needed to make the flash message
                              work that we talked about in the "music_controller.rb"
                              this one is related to the "def destroy" part of the
                              controller. See the comments in the "music_controller.rb"
                              file for more information.-->

<%= yield %>

</body>
</html>

app/views/musics/edit.html.erb
<%= form_for @music do |f| %>
<% if @music.errors.any? %>
  <ul>
    <% @music.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<% end %>

     <!--Lines 1-9 - This is the second batch of code which relates to the validations 
         in the "music.rb" model file.  It is the second batch of code needed
         to make the validations work properly so that you can get errors
         on the edit page in the browser after hitting the submit button. The code
         in the "new.html.erb" file between lines 1 and 9 is (in this case)
         identical to the code in this file-->


<%= form_for @music do |f| %>
<br>
<%= f.label :song %>
<%= f.text_field :song %>
<br>
<br>
<%= f.label :artist %>
<%= f.text_field :artist %>
<br>
<br>
<%= f.submit "Submit edit" %>
<hr>
<%= link_to "Meh, remove this bitch", music_path(@music),
data: {confirm: "Are you sure you want to remove this bitch?"}, method: "delete" %>
|
<%= link_to "Back to playlist", root_path %>
<% end %>

app/views/musics/index.html.erb
<h1>Edit Playlist</h1>
<hr>

<% @musics.each do |music| %>
<%= music.artist %> - <%= music.song %>
<br>

<%= link_to "View song info", music_path(music)  %>
|
<%= link_to "Remove song", music_path(music),
data: {confirm: "Are you sure you want to remove this song?"}, method: "delete" %>

      <!--Data Confrims line 11 - able to be added in a link_to erb tag for a confirmation
          popup window.-->

|
<%= link_to "Edit song", edit_music_path(music) %>

<hr>
<% end %>

<%= link_to "Add another song", new_music_path %>
|
<%= link_to "Back to playlist", root_path %>

app/views/musics/new.html.erb
<%= form_for @music do |f| %>
<% if @music.errors.any? %>
  <ul>
    <% @music.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<% end %>

    <!--Lines 1-9 - This is the second batch of code which relates to the validations
        in the "music.rb" model file.  It is the second batch of code needed
        to make the validations work properly so that you can get errors
        on the page in the browser after hitting the submit button to create a new song.
        The code in the "edit.html.erb" file between lines 1 and 9 is (in this case)
        identical to the code in this file-->


<%= form_for @music do |f| %>
<br>
<%= f.label :song %>
<%= f.text_field :song %>
<br>
<br>
<%= f.label :artist %>
<%= f.text_field :artist %>
<br>
<br>
<%= f.submit "Add this song to my playlist" %>
<% end %>
<hr>
<%= link_to "Edit playlist", musics_path %>
|
<%= link_to "Back to playlist", root_path %>

app/views/musics/show.html.erb
<br>
<%= @music.artist %> - <%= @music.song %>
<hr>

<%= link_to "Edit song", edit_music_path(@music) %>
|
<%= link_to "Edit playlist", musics_path %>
|
<%= link_to "Remove song", music_path(@music),
data: {confirm: "Are you sure you want to remove this song?"}, method: "delete" %>

    <!--Data Confrims line 10 - able to be added in a link_to erb tag for a confirmation
        popup window.-->

|
<%= link_to "Back to playlist", root_path %>

app/views/musics/thelist.html.erb
<h1>My Playlist</h1>
<hr>
<% @musics.each do |music| %>
<%= music.artist %> - <%= music.song %>
<br>
<% end %>

<hr>
<%= link_to "Paylist options", musics_path %>